<%@page contentType="text/html" pageEncoding="UTF-8"%><%@taglib prefix="c" uri="http://java.sun.com/jsp/jstl/core"%><%@taglib prefix="fmt" uri="http://java.sun.com/jsp/jstl/fmt"%>
<!DOCTYPE html><html><head><meta charset="UTF-8"><meta name="viewport" content="width=device-width, initial-scale=1.0"><title>Rental Discounts - Admin</title><link rel="stylesheet" href="${pageContext.request.contextPath}/assets/css/admin.css"></head><body class="admin-body"><div class="admin-shell"><%@ include file="/WEB-INF/jspf/admin-sidebar.jspf" %><main class="admin-main"><%@ include file="/WEB-INF/jspf/admin-topbar.jspf" %><div class="admin-content">
<section class="admin-panel"><div class="admin-panel-header"><div><h2>Rental Discount Usage</h2><p>Read-only audit of discount codes applied to rentals.</p></div></div>
<form class="form-row" action="${pageContext.request.contextPath}/" method="GET"><input type="hidden" name="action" value="admin-rental-discounts"><input type="search" name="keyword" value="${keyword}" placeholder="Search rental, customer, email, or discount code"><button class="admin-button" type="submit">Filter</button></form>
<div class="admin-table-wrap"><table class="admin-table"><thead><tr><th>Usage ID</th><th>Rental</th><th>Customer</th><th>Discount</th><th>Rental Period</th><th>Actions</th></tr></thead><tbody>
<c:forEach var="item" items="${rentalDiscounts}"><tr><td><strong><c:out value="${item.rentalDiscountId}"/></strong></td><td><c:out value="${item.rentalId}"/></td><td><c:out value="${item.customerName}"/><br><small><c:out value="${item.customerEmail}"/></small></td><td><span class="status-chip"><c:out value="${item.discountCode}"/> - <c:out value="${item.discountPercent}"/>%</span></td><td><fmt:formatDate value="${item.startDate}" pattern="dd/MM/yyyy"/> - <fmt:formatDate value="${item.endDate}" pattern="dd/MM/yyyy"/></td><td><a class="admin-button light" href="${pageContext.request.contextPath}?action=admin-rental-discount-detail&id=${item.rentalDiscountId}">View</a></td></tr></c:forEach>
<c:if test="${empty rentalDiscounts}"><tr><td colspan="6">No rental discount usage found.</td></tr></c:if>
</tbody></table></div><%@ include file="/WEB-INF/jspf/admin-pagination.jspf" %></section>
</div></main></div></body></html>
