<%@page contentType="text/html" pageEncoding="UTF-8"%><%@taglib prefix="c" uri="http://java.sun.com/jsp/jstl/core"%>
<!DOCTYPE html><html><head><meta charset="UTF-8"><meta name="viewport" content="width=device-width, initial-scale=1.0"><title>${empty charge ? 'Create Extra Charge' : 'Edit Extra Charge'} - Admin</title><link rel="stylesheet" href="${pageContext.request.contextPath}/assets/css/admin.css"></head><body class="admin-body"><div class="admin-shell"><%@ include file="/WEB-INF/jspf/admin-sidebar.jspf" %><main class="admin-main"><%@ include file="/WEB-INF/jspf/admin-topbar.jspf" %><div class="admin-content">
<c:if test="${not empty adminError}"><div class="admin-message error"><c:out value="${adminError}"/></div></c:if>
<section class="admin-panel"><div class="admin-panel-header"><div><h2>${empty charge ? 'Create Extra Charge' : 'Edit Extra Charge'}</h2><p>Only unpaid charges can be changed. Paid records stay locked for finance history.</p></div><a class="admin-button light" href="${pageContext.request.contextPath}?action=admin-extra-charges">Back</a></div>
<form class="admin-form" action="${pageContext.request.contextPath}/admin/extra-charges/save" method="POST"><input type="hidden" name="chargeId" value="${charge.chargeId}"><div class="admin-form-grid">
<c:choose><c:when test="${empty charge}"><div class="admin-field full"><label>Rental</label><select name="rentalId" required><option value="">Choose eligible rental</option><c:forEach var="rental" items="${eligibleRentals}"><option value="${rental.rentalId}">${rental.rentalId} - ${rental.customer.fullName} - ${rental.vehicle.model.name} ${rental.vehicle.licensePlate}</option></c:forEach></select></div></c:when><c:otherwise><input type="hidden" name="rentalId" value="${charge.rentalId}"><div class="admin-field full"><label>Rental</label><input type="text" value="${charge.rentalId} - ${charge.customerName}" disabled></div></c:otherwise></c:choose>
<div class="admin-field"><label>Charge Type</label><select name="chargeType" required><c:forEach var="item" items="${chargeTypes}"><option value="${item}" ${charge.chargeType == item ? 'selected' : ''}>${item}</option></c:forEach></select></div>
<div class="admin-field"><label>Amount</label><input class="money-display-input" id="extraChargeAmountDisplay" type="text" inputmode="numeric" value="${charge.amount}" data-money-target="amount" data-money-min="1" required><input type="hidden" id="amount" name="amount" value="${charge.amount}"></div>
<div class="admin-field full"><label>Description</label><textarea name="description" required rows="4"><c:out value="${charge.description}"/></textarea></div>
</div><div class="admin-form-actions"><button class="admin-button" type="submit">Save Charge</button><a class="admin-button light" href="${pageContext.request.contextPath}?action=admin-extra-charges">Cancel</a></div></form>
</section></div></main></div><script src="${pageContext.request.contextPath}/assets/js/money-input.js"></script></body></html>
