<%@page contentType="text/html" pageEncoding="UTF-8"%><%@taglib prefix="c" uri="http://java.sun.com/jsp/jstl/core"%><%@taglib prefix="fmt" uri="http://java.sun.com/jsp/jstl/fmt"%>
<!DOCTYPE html><html><head><meta charset="UTF-8"><meta name="viewport" content="width=device-width, initial-scale=1.0"><title>Extra Charges - Admin</title><link rel="stylesheet" href="${pageContext.request.contextPath}/assets/css/admin.css"></head><body class="admin-body"><div class="admin-shell"><%@ include file="/WEB-INF/jspf/admin-sidebar.jspf" %><main class="admin-main"><%@ include file="/WEB-INF/jspf/admin-topbar.jspf" %><div class="admin-content">
<c:if test="${not empty adminSuccess}"><div class="admin-message success"><c:out value="${adminSuccess}"/></div></c:if><c:if test="${not empty adminError}"><div class="admin-message error"><c:out value="${adminError}"/></div></c:if>
<section class="admin-panel"><div class="admin-panel-header"><div><h2>Extra Charge Management</h2><p>Review late, damage, cleaning, accessory, and system-generated charges.</p></div></div>
<form class="form-row" action="${pageContext.request.contextPath}/" method="GET"><input type="hidden" name="action" value="admin-extra-charges"><input type="search" name="keyword" value="${keyword}" placeholder="Search charge, rental, customer, vehicle"><select name="type"><option value="ALL">All Types</option><c:forEach var="item" items="${chargeTypes}"><option value="${item}" ${selectedType == item.name() ? 'selected' : ''}>${item}</option></c:forEach></select><select name="status"><option value="ALL">All Statuses</option><c:forEach var="item" items="${chargeStatuses}"><option value="${item}" ${selectedStatus == item.name() ? 'selected' : ''}>${item}</option></c:forEach></select><button class="admin-button" type="submit">Filter</button></form>
<div class="admin-table-wrap"><table class="admin-table"><thead><tr><th>Charge</th><th>Customer</th><th>Vehicle</th><th>Type</th><th>Amount</th><th>Status</th><th>Created</th><th>Actions</th></tr></thead><tbody>
<c:forEach var="charge" items="${charges}"><tr><td><strong><c:out value="${charge.chargeId}"/></strong><br><small><c:out value="${charge.rentalId}"/></small></td><td><c:out value="${charge.customerName}"/><br><small><c:out value="${charge.customerEmail}"/></small></td><td><c:out value="${charge.vehicleName}"/> - <c:out value="${charge.licensePlate}"/></td><td><c:out value="${charge.chargeType}"/></td><td><fmt:formatNumber value="${charge.amount}" pattern="#,##0"/> VND</td><td><span class="status-chip"><c:out value="${charge.status}"/></span></td><td><fmt:formatDate value="${charge.createdAt}" pattern="dd/MM/yyyy HH:mm"/></td><td><div class="inline-actions"><a class="admin-button light" href="${pageContext.request.contextPath}?action=admin-extra-charge-detail&id=${charge.chargeId}">View</a><c:if test="${charge.canEdit}"><a class="admin-button light" href="${pageContext.request.contextPath}?action=admin-extra-charge-form&id=${charge.chargeId}">Edit</a></c:if><c:if test="${charge.canCancel}"><form class="inline-form" method="POST" action="${pageContext.request.contextPath}/admin/extra-charges/cancel" onsubmit="return confirm('Cancel this extra charge?');"><input type="hidden" name="chargeId" value="${charge.chargeId}"><button class="danger-button" type="submit">Cancel</button></form></c:if></div></td></tr></c:forEach>
<c:if test="${empty charges}"><tr><td colspan="8">No extra charges found.</td></tr></c:if>
</tbody></table></div><%@ include file="/WEB-INF/jspf/admin-pagination.jspf" %></section>
</div></main></div></body></html>
