<%@page contentType="text/html" pageEncoding="UTF-8"%><%@taglib prefix="c" uri="http://java.sun.com/jsp/jstl/core"%><%@taglib prefix="fmt" uri="http://java.sun.com/jsp/jstl/fmt"%>
<!DOCTYPE html><html><head><meta charset="UTF-8"><meta name="viewport" content="width=device-width, initial-scale=1.0"><title>Maintenance - Admin</title><link rel="stylesheet" href="${pageContext.request.contextPath}/assets/css/admin.css"></head><body class="admin-body"><div class="admin-shell"><%@ include file="/WEB-INF/jspf/admin-sidebar.jspf" %><main class="admin-main"><%@ include file="/WEB-INF/jspf/admin-topbar.jspf" %><div class="admin-content">
<c:if test="${not empty adminSuccess}"><div class="admin-message success"><c:out value="${adminSuccess}"/></div></c:if><c:if test="${not empty adminError}"><div class="admin-message error"><c:out value="${adminError}"/></div></c:if>
<section class="admin-panel"><div class="admin-panel-header"><div><h2>Maintenance Management</h2><p>Track vehicles that are unavailable because they need inspection or repair.</p></div><a class="admin-button" href="${pageContext.request.contextPath}?action=admin-maintenance-form">Create Maintenance</a></div>
<form class="form-row" action="${pageContext.request.contextPath}/" method="GET"><input type="hidden" name="action" value="admin-maintenance"><input type="search" name="keyword" value="${keyword}" placeholder="Search vehicle, station, maintenance"><select name="status"><option value="ALL">All Statuses</option><c:forEach var="item" items="${maintenanceStatuses}"><option value="${item}" ${selectedStatus == item.name() ? 'selected' : ''}>${item}</option></c:forEach></select><button class="admin-button" type="submit">Filter</button></form>
<div class="admin-table-wrap"><table class="admin-table"><thead><tr><th>Maintenance</th><th>Vehicle</th><th>Station</th><th>Status</th><th>Vehicle Status</th><th>Date</th><th>Actions</th></tr></thead><tbody>
<c:forEach var="item" items="${maintenanceRecords}"><tr><td><strong><c:out value="${item.maintenanceId}"/></strong><br><small><c:out value="${item.description}"/></small></td><td><c:out value="${item.modelName}"/> - <c:out value="${item.licensePlate}"/></td><td><c:out value="${item.stationName}"/></td><td><span class="status-chip"><c:out value="${item.status}"/></span></td><td><span class="status-chip"><c:out value="${item.vehicleStatus}"/></span></td><td><fmt:formatDate value="${item.maintenanceDate}" pattern="dd/MM/yyyy HH:mm"/></td><td><div class="inline-actions"><a class="admin-button light" href="${pageContext.request.contextPath}?action=admin-maintenance-detail&id=${item.maintenanceId}">View</a><c:if test="${item.canComplete}"><form class="inline-form" method="POST" action="${pageContext.request.contextPath}/admin/maintenance/complete" onsubmit="return confirm('Mark this maintenance as completed?');"><input type="hidden" name="maintenanceId" value="${item.maintenanceId}"><button class="admin-button" type="submit">Mark Completed</button></form></c:if></div></td></tr></c:forEach>
<c:if test="${empty maintenanceRecords}"><tr><td colspan="7">No maintenance records found.</td></tr></c:if>
</tbody></table></div><%@ include file="/WEB-INF/jspf/admin-pagination.jspf" %></section>
</div></main></div></body></html>
