<%@page contentType="text/html" pageEncoding="UTF-8"%><%@taglib prefix="c" uri="http://java.sun.com/jsp/jstl/core"%><%@taglib prefix="fmt" uri="http://java.sun.com/jsp/jstl/fmt"%>
<!DOCTYPE html><html><head><meta charset="UTF-8"><meta name="viewport" content="width=device-width, initial-scale=1.0"><title>Status History - Admin</title><link rel="stylesheet" href="${pageContext.request.contextPath}/assets/css/admin.css"></head><body class="admin-body"><div class="admin-shell"><%@ include file="/WEB-INF/jspf/admin-sidebar.jspf" %><main class="admin-main"><%@ include file="/WEB-INF/jspf/admin-topbar.jspf" %><div class="admin-content">
<c:if test="${not empty adminError}"><div class="admin-message error"><c:out value="${adminError}"/></div></c:if>
<section class="admin-panel"><div class="admin-panel-header"><div><h2>Rental Status History</h2><p>Read-only timeline of rental status changes.</p></div></div>
<form class="form-row" action="${pageContext.request.contextPath}/" method="GET"><input type="hidden" name="action" value="admin-rental-status-history"><input type="search" name="keyword" value="${keyword}" placeholder="Search rental, customer, vehicle"><select name="status"><option value="ALL">All Statuses</option><c:forEach var="item" items="${rentalStatuses}"><option value="${item}" ${selectedStatus == item.name() ? 'selected' : ''}>${item}</option></c:forEach></select><input type="date" name="startDate" value="${startDate}"><input type="date" name="endDate" value="${endDate}"><button class="admin-button" type="submit">Filter</button></form>
<div class="admin-table-wrap"><table class="admin-table"><thead><tr><th>History ID</th><th>Rental</th><th>Customer</th><th>Vehicle</th><th>Status</th><th>Changed At</th><th>Actions</th></tr></thead><tbody>
<c:forEach var="item" items="${historyRows}"><tr><td><strong><c:out value="${item.historyId}"/></strong></td><td><c:out value="${item.rentalId}"/></td><td><c:out value="${item.customerName}"/><br><small><c:out value="${item.customerEmail}"/></small></td><td><c:out value="${item.vehicleName}"/> - <c:out value="${item.licensePlate}"/></td><td><span class="status-chip"><c:out value="${item.status}"/></span></td><td><fmt:formatDate value="${item.changedAt}" pattern="dd/MM/yyyy HH:mm"/></td><td><a class="admin-button light" href="${pageContext.request.contextPath}?action=admin-rental-status-history-detail&id=${item.historyId}">View</a></td></tr></c:forEach>
<c:if test="${empty historyRows}"><tr><td colspan="7">No status history found.</td></tr></c:if>
</tbody></table></div><%@ include file="/WEB-INF/jspf/admin-pagination.jspf" %></section>
</div></main></div></body></html>
