<%@page contentType="text/html" pageEncoding="UTF-8"%><%@taglib prefix="c" uri="http://java.sun.com/jsp/jstl/core"%><%@taglib prefix="fmt" uri="http://java.sun.com/jsp/jstl/fmt"%>
<!DOCTYPE html><html><head><meta charset="UTF-8"><meta name="viewport" content="width=device-width, initial-scale=1.0"><title>Wallet Transactions - Admin</title><link rel="stylesheet" href="${pageContext.request.contextPath}/assets/css/admin.css"></head><body class="admin-body"><div class="admin-shell"><%@ include file="/WEB-INF/jspf/admin-sidebar.jspf" %><main class="admin-main"><%@ include file="/WEB-INF/jspf/admin-topbar.jspf" %><div class="admin-content">
<c:if test="${not empty adminError}"><div class="admin-message error"><c:out value="${adminError}"/></div></c:if>
<section class="admin-panel"><div class="admin-panel-header"><div><h2>Wallet Transactions</h2><p>Read-only wallet cashflow audit: topups, payments, and refunds.</p></div></div>
<form class="form-row" action="${pageContext.request.contextPath}/" method="GET"><input type="hidden" name="action" value="admin-wallet-transactions"><input type="search" name="keyword" value="${keyword}" placeholder="Search customer, wallet, transaction, description"><select name="type"><option value="ALL">All Types</option><c:forEach var="item" items="${transactionTypes}"><option value="${item}" ${selectedType == item.name() ? 'selected' : ''}>${item}</option></c:forEach></select><input type="date" name="startDate" value="${startDate}"><input type="date" name="endDate" value="${endDate}"><button class="admin-button" type="submit">Filter</button></form>
<div class="admin-table-wrap"><table class="admin-table"><thead><tr><th>Transaction</th><th>Wallet</th><th>Customer</th><th>Type</th><th>Amount</th><th>Description</th><th>Created</th><th>Actions</th></tr></thead><tbody>
<c:forEach var="item" items="${walletTransactions}"><tr><td><strong><c:out value="${item.transactionId}"/></strong></td><td><c:out value="${item.walletId}"/></td><td><c:out value="${item.customerName}"/><br><small><c:out value="${item.customerEmail}"/></small></td><td><span class="status-chip"><c:out value="${item.type}"/></span></td><td><fmt:formatNumber value="${item.amount}" pattern="#,##0"/> VND</td><td><c:out value="${item.description}"/></td><td><fmt:formatDate value="${item.createdAt}" pattern="dd/MM/yyyy HH:mm"/></td><td><a class="admin-button light" href="${pageContext.request.contextPath}?action=admin-wallet-transaction-detail&id=${item.transactionId}">View</a></td></tr></c:forEach>
<c:if test="${empty walletTransactions}"><tr><td colspan="8">No wallet transactions found.</td></tr></c:if>
</tbody></table></div><%@ include file="/WEB-INF/jspf/admin-pagination.jspf" %></section>
</div></main></div></body></html>
