<%@page contentType="text/html" pageEncoding="UTF-8"%><%@taglib prefix="c" uri="http://java.sun.com/jsp/jstl/core"%><%@taglib prefix="fmt" uri="http://java.sun.com/jsp/jstl/fmt"%>
<!DOCTYPE html><html><head><meta charset="UTF-8"><meta name="viewport" content="width=device-width, initial-scale=1.0"><title>Reviews - Admin</title><link rel="stylesheet" href="${pageContext.request.contextPath}/assets/css/admin.css"></head><body class="admin-body"><div class="admin-shell"><%@ include file="/WEB-INF/jspf/admin-sidebar.jspf" %><main class="admin-main"><%@ include file="/WEB-INF/jspf/admin-topbar.jspf" %><div class="admin-content">
<section class="admin-panel"><div class="admin-panel-header"><div><h2>Review Management</h2><p>Read customer feedback by model and rental.</p></div></div>
<form class="form-row" action="${pageContext.request.contextPath}/" method="GET"><input type="hidden" name="action" value="admin-reviews"><input type="search" name="keyword" value="${keyword}" placeholder="Search customer, model, or comment"><select name="rating"><option value="ALL">All Ratings</option><c:forEach begin="1" end="5" var="star"><option value="${star}" ${selectedRating == star ? 'selected' : ''}>${star} Star</option></c:forEach></select><button class="admin-button" type="submit">Filter</button></form>
<div class="admin-table-wrap"><table class="admin-table"><thead><tr><th>Review</th><th>Customer</th><th>Model</th><th>Rating</th><th>Comment</th><th>Created</th><th>Actions</th></tr></thead><tbody>
<c:forEach var="review" items="${reviews}"><tr><td><strong><c:out value="${review.reviewId}"/></strong><br><small><c:out value="${review.rentalId}"/></small></td><td><c:out value="${review.customerName}"/><br><small><c:out value="${review.customerEmail}"/></small></td><td><c:out value="${review.modelName}"/></td><td><span class="status-chip"><c:out value="${review.rating}"/> / 5</span></td><td><c:out value="${review.comment}"/></td><td><fmt:formatDate value="${review.createdAt}" pattern="dd/MM/yyyy HH:mm"/></td><td><a class="admin-button light" href="${pageContext.request.contextPath}?action=admin-review-detail&id=${review.reviewId}">View</a></td></tr></c:forEach>
<c:if test="${empty reviews}"><tr><td colspan="7">No reviews found.</td></tr></c:if>
</tbody></table></div><%@ include file="/WEB-INF/jspf/admin-pagination.jspf" %></section>
</div></main></div></body></html>
